name: ${pluginName}
version: ${version}
main: com.willfp.actions.ActionsPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
depend:
  - eco
softdepend:
  - libreforge
commands:
  actions:
    description: Base Command
    permission: actions.command.actions

permissions:
  actions.*:
    description: All actions permissions
    default: op
    children:
      actions.command.*: true
  actions.command.*:
    description: All commands
    default: op
    children:
      actions.command.actions: true
      actions.command.reload: true

  actions.command.reload:
    description: Allows reloading the config
    default: op
